// Allow-list of valid nutrient ids for the custom ingredient library API.
// MUST stay in sync with src/nutrition/types/nutrients.ts (NutrientId union).
// Duplicated here (plain JS) because the server runs standalone under Node,
// without the TypeScript build step, and only needs the id strings.
export const NUTRIENT_IDS = [
  "totalFat",
  "saturatedFat",
  "transFat",
  "totalCarbohydrate",
  "dietaryFiber",
  "solubleFiber",
  "insolubleFiber",
  "totalSugars",
  "addedSugars",
  "sugarAlcohol",
  "protein",
  "cholesterol",
  "sodium",
  "vitaminD",
  "calcium",
  "iron",
  "potassium",
  "vitaminA",
  "vitaminC",
  "vitaminE",
  "vitaminK",
  "thiamin",
  "riboflavin",
  "niacin",
  "vitaminB6",
  "folate",
  "vitaminB12",
  "biotin",
  "pantothenicAcid",
  "phosphorus",
  "iodine",
  "magnesium",
  "zinc",
  "selenium",
  "copper",
  "manganese",
  "chromium",
  "molybdenum",
  "chloride",
  "choline",
];
